### ISSUE TITLE
IE8报错“缺少标识符、字符串或数字”

### ISSUE THREAD

**Issue by xx7y7xx** [tomieric/react-ie8-boilerplate#2]
```
缺少标识符、字符串或数字
bundle-858d0ba8fec2e3e51430.js
```

发现是`bundle-858d0ba8fec2e3e51430.js`中包含了如下代码

```js
function t(e){return e&&e.__esModule?e:{default:e}}
```

因为`default`在IE8下是关键字，所以出现如上错误了。但是我发现你已经在`postLoads`中添加了`es3ify-loader`，按理说`{default:e}`应该已经自动替换成了`{"default":e}`，不应该出现这个问题。

后来经过测试，我发现把`webpack.optimize.UglifyJsPlugin`注释掉就没有问题了，代码如下

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
```

但是我对UglifyJS不熟悉，所以不知道是否有选项能把这个功能关掉。

**Comment by xx7y7xx** [comment]
查看了一下使用的uglify-js是2.7.5

```
├─┬ webpack@1.14.0
...
│ ├─┬ uglify-js@2.7.5
```

Google了一下，发现了一个类似的问题：https://www.bugmuncher.com/blog/ember-js-in-ie8/
是因为UglifyJS的`--screw-ie8`参数默认值改成了`true`（默认放弃支持IE8）

查看了一下UglifyJS的提交记录，是在https://github.com/mishoo/UglifyJS2/commit/02c638209ee22816b1324ff0c0f47b27db1336af
修改了参数默认值。

**Comment by tomieric** [comment]
`default` 默认有`es3ify-loader`去解决

但`i.default`只能 设置了

```
manage: false
```

还有就是不能设置注释的压缩配置

修改查看: [https://github.com/tomieric/react-ie8-boilerplate/commit/552efc4e301945457c922a85b49bb2f1780c8239](https://github.com/tomieric/react-ie8-boilerplate/commit/552efc4e301945457c922a85b49bb2f1780c8239)
